language: node_js
node_js:
  - 'stable'
install: npm install
cache:
  directories:
    - 'node_modules'
env:
  global:
    - DB_ENV=testing
services:
  - postgresql
before_script:
  - psql -c 'create database cookbook_test;' -U postgres
  - psql -c "CREATE USER username WITH PASSWORD 'password';" -U postgres

script: npm test
notifications:
  email: false
